name: Build and Analyze

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt-openjdk'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      - name: Build with Maven
        run: mvn clean install

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.projectKey=<YOUR_PROJECT_KEY>
            -Dsonar.organization=<YOUR_ORG>
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run tests
        run: mvn test
